---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myddnstls
  namespace: default
spec:
  dnsNames:
    - tongli.myddns.me
  secretName: myddns-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
