# Use named ingress for http01 resolver
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # server: https://acme-v02.api.letsencrypt.org/directory
    # preferredChain: "ISRG Root X1"
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: email4tong@yahoo.com
    privateKeySecretRef:
      name: letencrypt-secret
    solvers:
    - http01:
        ingress:
          name: external-balancer
